### ISSUE TITLE
Some issues with transformation result

### ISSUE THREAD

**Issue by rogargon** [raultds/TFG-RDF-Transformer-webapp#10]
Given the following mapping configuration:
![image](https://user-images.githubusercontent.com/1313870/81207740-54628880-8fce-11ea-9280-57a20012c2f7.png)

The obtained output has some issues, which are described after each line:

```
<http://gfbi.udl.cat/Korea//8138>
```

> Here, check first if the URI provided by the user ends already with '/' and then do not add it. The same if it ends with '#'

```
        <http://dbpedia.org/ontology/continent>
                "South%20America" ;
```
> Regarding Text literals, the text should not be URL encoded as it is not part of an URL. It should be the same text than in the corresponding cell, in this case, `"South America"`
```
        <http://dbpedia.org/ontology/country>
                "Mexico" ;
        <http://dbpedia.org/ontology/diameter>
                "41"^^<http://www.w3.org/2001/XMLSchema#decimal> ;
        <http://dbpedia.org/ontology/species>
                "Quercus" ;
        <http://open.vocab.org/terms/hasPlot>
                "157" ;
        <http://purl.org/linked-data/sdmx/2009/dimension#refArea>
                0.25 ;
```
> The choice for this column is "NonInteger" which corresponds to a decimal. Like in the previous case, the output should be `"0.25"^^<http://www.w3.org/2001/XMLSchema#decimal> ;`
```
        <http://www.w3.org/2003/01/geo/wgs84_pos#lat>
                24.01840111645682 ;
```
> The same, the output should be `"24.01840111645682"^^<http://www.w3.org/2001/XMLSchema#decimal> ;`
```
        <http://www.w3.org/2003/01/geo/wgs84_pos#long>
                -105.79902753782987 ;
```
> The same, the output should be `"-105.7990275378298"^^<http://www.w3.org/2001/XMLSchema#decimal> ;`
```
        <http://www.w3.org/2006/time#year>
                "2009"^^<http://www.w3.org/2001/XMLSchema#int> .
```

After all these changes, the output should be something like:

```
<http://gfbi.udl.cat/Korea/8138>
        <http://dbpedia.org/ontology/continent>
                "South America" ;
        <http://dbpedia.org/ontology/country>
                "Mexico" ;
        <http://dbpedia.org/ontology/diameter>
                "41"^^<http://www.w3.org/2001/XMLSchema#decimal> ;
        <http://dbpedia.org/ontology/species>
                "Quercus" ;
        <http://open.vocab.org/terms/hasPlot>
                "157" ;
        <http://purl.org/linked-data/sdmx/2009/dimension#refArea>
                "0.25"^^<http://www.w3.org/2001/XMLSchema#decimal> ;
        <http://www.w3.org/2003/01/geo/wgs84_pos#lat>
                "24.01840111645682"^^<http://www.w3.org/2001/XMLSchema#decimal> ;
        <http://www.w3.org/2003/01/geo/wgs84_pos#long>
                "-105.7990275378298"^^<http://www.w3.org/2001/XMLSchema#decimal> ;
        <http://www.w3.org/2006/time#year>
                "2009"^^<http://www.w3.org/2001/XMLSchema#int> .
```

**Comment by raultds** [comment]
Fixed the uri problem.

About the decimal problem. I found that when I use XSD:Decimal as a datatype Jena rounds the number, but when I use double or float datatype it shows as it should.

Do you think this is a reasonable solution?

**Comment by rogargon** [comment]
OK, then better to switch to xsd:float
