### ISSUE TITLE
Add Resource as value type choice option

### ISSUE THREAD

**Issue by rogargon** [raultds/TFG-RDF-Transformer-webapp#13]
The value of a column might be a data type but it can be also the identifier (URI) for a related resource. To support this, add "Resource" as a choice beyond Integer, Text,...

In this case, instead of a Literal, a Resource should be generated as the object of the triple. The text of the cell should be used to generate the URI of the object Resource. In this case, it should be URL encoded to generate a valid URI.

For instance, if the SPCD column is defined to generate Resource values instead of text literals, the resulting RDF should be something like:

```
<http://gfbi.udl.cat/Korea/138>
        <http://dbpedia.org/ontology/species>
                <http://gfbi.udl.cat/Korea/Picea%20chihuahuana> .
```

**Comment by raultds** [comment]
Right now I treat the resource datatype as a string and it inputs the following:
`<http://myuri.com/Monasterio%20y%20Real%20Sitio%20de%20El%20Escorial.> 
        <http://purl.org/dc/terms/hasFormat> "http://www.mecd.gob.es/cultura-mecd/areas-cultura/patrimonio/mc/patrimoniomundial/bienes-declarados/por-ano-de-inscripcion/escorial.html" .`

I know this is not what you expect but currently I think jena doesn't allow to put a resource as a property of a resource (if I'm not mistaken, at least I couldn't find how).

**Comment by rogargon** [comment]
With Jena there is a generic method Model.add(...) to add triples resource objects:

https://jena.apache.org/documentation/javadoc/jena/org/apache/jena/rdf/model/ModelCon.html#add-org.apache.jena.rdf.model.Resource-org.apache.jena.rdf.model.Property-org.apache.jena.rdf.model.RDFNode-

There is a full example in the documentation intro (https://jena.apache.org/tutorials/rdf_api.html#ch-Introduction):

```
Model m = ModelFactory.createDefaultModel();
 String nsA = "http://somewhere/else#";
 String nsB = "http://nowhere/else#";
 Resource root = m.createResource( nsA + "root" );
 Property P = m.createProperty( nsA + "P" );
 Property Q = m.createProperty( nsB + "Q" );
 Resource x = m.createResource( nsA + "x" );
 Resource y = m.createResource( nsA + "y" );
 Resource z = m.createResource( nsA + "z" );
 m.add( root, P, x ).add( root, P, y ).add( y, Q, z );
```



It is also possible to add triples with literal values and their datatypes:

https://jena.apache.org/documentation/javadoc/jena/org/apache/jena/rdf/model/ModelCon.html#add-org.apache.jena.rdf.model.Resource-org.apache.jena.rdf.model.Property-java.lang.String-org.apache.jena.datatypes.RDFDatatype-

**Comment by raultds** [comment]
Updated API to generate correctly the resources
