### ISSUE TITLE
Improve readability of transformation view

### ISSUE THREAD

**Issue by rogargon** [raultds/TFG-RDF-Transformer-webapp#4]
It is hard to read this screen because the contrast between the foreground and background is small. It might be better to make the background lighter, white, or light grey. Then, grey and thinner borders for the table.

![image](https://user-images.githubusercontent.com/1313870/81184226-73522200-8fb0-11ea-963a-5033d8ec4942.png)

**Comment by raultds** [comment]
I made a full visual refactor of the app on the branch "visual-refactor" that should solve this problem and updates the general looks of the app. Please take a look @rogargon  .

**Comment by rogargon** [comment]
Looks fine, good job
