### ISSUE TITLE
Define minimum column wide or make it resizable

### ISSUE THREAD

**Issue by rogargon** [raultds/TFG-RDF-Transformer-webapp#6]
Currently, if the column name is short, like "PLT", the column is so narrow that it is hard to see or interact with it. For instance:

![image](https://user-images.githubusercontent.com/1313870/81188185-4f450f80-8fb5-11ea-875c-fda7bfce2775.png)

**Comment by raultds** [comment]
I made a full visual refactor of the app on the branch "visual-refactor" that should solve this problem and updates the general looks of the app. Please take a look @rogargon  .
