### ISSUE TITLE
Improve readability of autocomplete

### ISSUE THREAD

**Issue by rogargon** [raultds/TFG-RDF-Transformer-webapp#7]
Showing the whole property URI makes it hard to read. It might be better to show to the user the "prefixedName" instead. The highlight obtained from the API might also help the user decide. So the autocomplete will show two lines for every result obtained from the API. For instance, for the following piece of JSON, the autocomplete would be something like:

**ei2a:graphicSurface**
> Graphic surface of a **plot** of land

```
{
      "prefixedName": [
        "ei2a:graphicSurface"
      ],
      "vocabulary.prefix": [
        "ei2a"
      ],
      "uri": [
        "http://opendata.aragon.es/def/ei2a#graphicSurface"
      ],
      "metrics.occurrencesInDatasets": [
        0
      ],
      "metrics.reusedByDatasets": [
        0
      ],
      "type": "property",
      "score": 0.4407255,
      "highlight": {
        "http://www.w3.org/2000/01/rdf-schema#comment@en": [
          "Graphic surface of a <b>plot</b> of land"
        ]
      }
    }
```

**Comment by raultds** [comment]
Now it looks like a standard dropdown
