### ISSUE TITLE
It should be possible to upload a file and start transformation if not logged in

### ISSUE THREAD

**Issue by rogargon** [raultds/TFG-RDF-Transformer-webapp#9]
If the user attempts to do that, redirect to the login/register form

**Comment by raultds** [comment]
I decided that a non registered user could still be able to attempt a transformation but the server won't store any info related about it.

If you think we should restrict the app to only registered users I can change it easily.

**Comment by rogargon** [comment]
No need to change that, but if the user is not registered I'm getting an error that seems to be related to not being logged in:

{timestamp: "2020-05-06T18:08:39.150+0000", status: 500, error: "Internal Server Error",…}
error: "Internal Server Error"
message: "No message available"
path: "/api/transform"
status: 500
timestamp: "2020-05-06T18:08:39.150+0000"
trace: "java.lang.NullPointerException↵	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:149)↵	at java.base/java.io.FileReader.<init>(FileReader.java:75)↵	at com.tfg.utils.CsvReader.convertFileToCsv(CsvReader.java:31)↵	at com.tfg.services.RDFService.createRDF(RDFService.java:63)↵	at com.tfg.controllers.FileUploadController.generateRDF(FileUploadController.java:64)↵	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)↵	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)↵	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)↵	at java.base/java.lang.reflect.Method.invoke(Method.java:566)↵	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)↵	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)↵	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)↵	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:893)↵	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:798)↵	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)↵	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)↵	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)↵	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)↵	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)↵	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)↵	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)↵	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)↵	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)↵	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)↵	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)↵	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)↵	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)↵	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)↵	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)↵	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)↵	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)↵	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119)↵	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)↵	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)↵	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)↵	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)↵	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)↵	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)↵	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)↵	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)↵	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)↵	at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:158)↵	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)↵	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)↵	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)↵	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)↵	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:97)↵	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)↵	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)↵	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:74)↵	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)↵	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)↵	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)↵	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)↵	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)↵	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)↵	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)↵	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)↵	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)↵	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)↵	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)↵	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)↵	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)↵	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)↵	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)↵	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)↵	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)↵	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)↵	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)↵	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)↵	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)↵	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:94)↵	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)↵	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)↵	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)↵	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)↵	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)↵	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)↵	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)↵	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)↵	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)↵	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:526)↵	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)↵	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)↵	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)↵	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)↵	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)↵	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)↵	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:860)↵	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1589)↵	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)↵	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)↵	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)↵	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)↵	at java.base/java.lang.Thread.run(Thread.java:834)↵"

**Comment by raultds** [comment]
I can't reproduce this issue. It works fine.

Maybe the issue is that you didn't change the file.upload-dir on the application.properties. So it returns null because it can't find a file. 
This should be added in the readme to avoid future problems
